development:
  adapter: postgresql
  encoding: unicode
  database: production_dump2
  pool: 5
  username: claudiug

staging:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: new_ecratum_test
  pool: 5
  username: ecra